language: java

cache:
  directories:
    - $HOME/.m2

services: docker

install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker run --rm -p 27017:27017 mongo
