@startuml
class ResourceObjectAdapter #orange

class NavigationAdapter #yellow {
    getNavigationItems()
}
class CollectionAdapter #yellow {
    getNextItems()
    getPreviousItems()
    getItems()
}
class ItemAdapter #yellow {
    getContent()
}
NavigationAdapter ..> ResourceObjectAdapter
ItemAdapter ..> ResourceObjectAdapter
CollectionAdapter ..> ResourceObjectAdapter
ResourceObjectAdapter ..> ResourceObject
@enduml