@startuml
class ResourceComponent

class CollectionComponent
class ItemComponent

ResourceComponent <|-- CollectionComponent
ResourceComponent <|-- ItemComponent

class CollectionAdapter
class ItemAdapter

CollectionComponent ..> CollectionAdapter
ItemComponent ..> ItemAdapter

note right of ResourceComponent: Can display a HAL resource.

@enduml
